### ISSUE TITLE
Heights

### ISSUE THREAD

**Issue by SpaceDiceMan** [LordEggNutz/Star-Wars-Generators#23]
Hi, 
the generated heights are a bit off. Even for SW way too often 3-4m tall humans...

**Comment by LordEggNutz** [comment]
Thanks for the report and apologies for the delay, I will work on this issue this weekend.

**Comment by LordEggNutz** [comment]
Moved to [HERE](https://github.com/LordEggNutz/Role-Playing-Game-Generators/issues/1)
